name: Android CI Build

on:
  push:
    branches: [ "main", "master" ] # Hangi branch'e kod atınca çalışsın?
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v4

    - name: Java'yı Kur (JDK 17)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Gradle'ı Çalıştırılabilir Yap
      run: chmod +x gradlew

    - name: Debug APK Derle
      run: ./gradlew assembleDebug

    - name: APK'yı GitHub'a Yükle (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
